w3c/webappsec-credential-management

- index.src.html
> Clarify the autocomplete attribute behavior.

- index.html
- index.src.html
> Fix input type for passwords

- index.html
- index.src.html
> Use [SecureContext] on interfaces

- index.html
- index.src.html
> Issue 20: Clarify unmediated get

- index.html
- index.src.html
This should address issue #64 .
> Replace RFC6454 references with HTML spec ones

- index.html
- index.src.html
@jyasskin, @battre: This is a simplified approach to aligning `Credential` creation across the various types. Let's talk about whether it could be reasonably extended in ways we're interested in.
> Define a 'create()' method on 'CredentialsContainer'.

- index.html
- index.src.html
@battre convinced me that there was not enough justification for removal
to cause the churn in existing code.
> Restore the constructors removed in #72.

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/jakearchibald/webappsec-credential-management/pull/117.html" title="Last updated on Dec 5, 2017, 9:19 AM GMT (9bb2f8d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/117/c3c4a91...jakearchibald:9bb2f8d.html" title="Last updated on Dec 5, 2017, 9:19 AM GMT (9bb2f8d)">Diff</a>
> JS syntax fixes

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/webappsec-credential-management/pull/124.html" title="Last updated on Jul 18, 2018, 11:17 PM GMT (5eac1b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/124/e62cb76...marcoscaceres:5eac1b3.html" title="Last updated on Jul 18, 2018, 11:17 PM GMT (5eac1b3)">Diff</a>
> fix: navigatior/navigator in examples

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/webappsec-credential-management/pull/121.html" title="Last updated on Jul 18, 2018, 10:10 PM GMT (d6d2279)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/121/e62cb76...marcoscaceres:d6d2279.html" title="Last updated on Jul 18, 2018, 10:10 PM GMT (d6d2279)">Diff</a>
> Fix typo: unambiguously

- index.html
index.html had not been updated along with AFAiCT a number of recent updates to index.src.html.  this is simply index.html built from the current index.src.html. 
will merging this auto-update https://w3c.github.io/webappsec-credential-management/ ?   I am guessing "yes", and @mkwst this morning said go ahead and merge...
> update index.html to match index.src.html

- index.html
- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/157.html" title="Last updated on Feb 19, 2021, 4:09 PM UTC (5cf393e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/157/ddd30f3...5cf393e.html" title="Last updated on Feb 19, 2021, 4:09 PM UTC (5cf393e)">Diff</a>
> Jeffh update editorship (rebuild index.html)

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/160.html" title="Last updated on Feb 20, 2021, 5:49 AM UTC (27626c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/160/a2b896e...27626c5.html" title="Last updated on Feb 20, 2021, 5:49 AM UTC (27626c5)">Diff</a>
> Meta: Change to "main" branch in Version History link

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/178.html" title="Last updated on Nov 16, 2021, 11:03 PM UTC (743f4f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/178/68a9134...743f4f6.html" title="Last updated on Nov 16, 2021, 11:03 PM UTC (743f4f6)">Diff</a>
> Add Nina Satragno as editor

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/198.html" title="Last updated on Apr 26, 2022, 11:57 PM UTC (68bd588)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/198/1de6ec0...68bd588.html" title="Last updated on Apr 26, 2022, 11:57 PM UTC (68bd588)">Diff</a>
> Mark Jeff as a former editor

- index.bs
Fixes https://github.com/fedidcg/FedCM/issues/301
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/201.html" title="Last updated on Jul 8, 2022, 1:43 PM UTC (fa4b0c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/201/878530d...fa4b0c8.html" title="Last updated on Jul 8, 2022, 1:43 PM UTC (fa4b0c8)">Diff</a>
> Add IdentityCredential to Credential Type Registry

- index.bs
Closes #222
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/232.html" title="Last updated on May 22, 2024, 1:02 AM UTC (376411a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/232/123c9ea...376411a.html" title="Last updated on May 22, 2024, 1:02 AM UTC (376411a)">Diff</a>
> Editorial: expand iff to if and only if

- index.bs
Closes #180
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/233.html" title="Last updated on May 22, 2024, 1:11 AM UTC (a5d35a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/233/123c9ea...a5d35a4.html" title="Last updated on May 22, 2024, 1:11 AM UTC (a5d35a4)">Diff</a>
> Editorial: use bikeshed shorthands

- .github/workflows/auto-publish.yml
Use latest Ubuntu, otherwise wrong bikeshed loads. 
See https://github.com/speced/bikeshed/issues/2861
> Chore: Update Ubuntu version

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/237.html" title="Last updated on May 23, 2024, 8:36 AM UTC (3d7dd5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/237/674c63c...3d7dd5d.html" title="Last updated on May 23, 2024, 8:36 AM UTC (3d7dd5d)">Diff</a>
> Do fully active check on Prevent Silent Access

- index.bs
Add Marcos to join editorial team.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/239.html" title="Last updated on Jun 7, 2024, 5:45 AM UTC (8b5470e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/239/4fa577c...8b5470e.html" title="Last updated on Jun 7, 2024, 5:45 AM UTC (8b5470e)">Diff</a>
> Chore: add Marcos to the editor's list
