w3c/webappsec-credential-management

- index.src.html
As pointed out in https://github.com/w3c/webappsec-credential-management/issues/26, there is a typo in step 9.3 of 3.1.3.1.
This patch fixes it as suggested.
> formData -> params in step 9.3 of 3.1.3.1

- index.src.html
@mikewest this valuable gem contains a fix to a typo (it's actually just a first CL to get me started).
Please review. Thanks.
> Fix typo (s/chosent/chosen/)

- index.html
- index.src.html
The PasswordCredential(form) constructor requires name attributes for the username/password fields. Fixes #15.
> Fix for issue 15: Some example code does not work

- index.html
- index.src.html
Fix example 2: The navigator.credentials.get call has a providers restriction to only return federated credentials from "https://federation.com" but then has a switch statement looking for facebook and accounts.google.com.
> Fix IDP selector in example 2.

- index.html
- index.src.html
Bikeshed complains that the variables inputBody, Content-Type, memory, undefined, init and
deep clone are only used once. The reasons are:
* undefined should actualy be a `<code>` not a `<var>` element, because it
expresses a JavaSCript constant, not a variable
* all the rest references external algorithms, which define them
Content-Type actually has multiple occurrences, but bikeshed apparently understands scopes
so that it picked the one where Content-Type only had one occurrence (which was a reference
to an external algorithm).
This patch marks all of those `<var>`s with the "ignore" attribute to silence the
warning. This is one step towards fixing https://github.com/w3c/webappsec-credential-management/issues/39.
Note that there is one more warning for the unique mention: for …
> Fix easy bikeshed warnings for index.html

- index.html
- index.src.html
This CL drops the input |types| from the "Request a Credential" algorithm,
because it is not used (instead, |types| is a local variable, value of which is
computed by the algorithm).
The CL also replaces "name" of an interface with a [[type]] shared by instances
implementing this interface. For PasswordCredential, for instance, "name" is
PasswordCredential, whereas [[type]] is "password". The latter corresponds to a
possible key in CredentialRequestOptions, which is what the algorithm expects.
This should fix issue #41.
> Clarify the "Request a Credential" algorithm

- index.html
- index.src.html
Change the PasswordCredential(form) constructor so that for common password-change forms that ask for the user's current-password and new-password only the new-password is adopted.
Fixes #34
> Fix PasswordCredential(form) constructor for password change forms

- index.html
- index.src.html
Instruct to call store() after get() to make PSL matched credentials eligible for unmediated access. I think it is useful to put this into the usecases section as web developers may copy & paste the code.
> Instruct to call store() after get()

- index.html
- index.src.html
This seems sane to me based on our discussion, @jyasskin. It might also resolve one of @leshi's concerns about the current shape of the API.
/cc @battre
> Replace the 'unmediated' bool with a 'mediation' enum.

- index.html
- index.src.html
I have created a pull request as discussed today.
Note that I have not renamed the require user mediation flag but the corresponding algorithm. I am a tiny big concerned that we are now using inconsistent naming (there are still a number of cases referring to mediation).
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/issue-74-rename-requireUserMediation.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/cad004e...8561d88.html)
> Rename requireUserMediation to preventSilentAccess

- index.html
- index.src.html
CL addresses issue #90
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/issue-90-remove-nullability.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/6258010...d1bd87e.html)
> Remove nullability in places where they are not necessary

- .gitignore
- index.html
- index.src.html
This builds on #104 (Thanks @angelokai!) and now follows the instructions in https://dom.spec.whatwg.org/#abortcontroller-api-integration to bail out early if the caller has already aborted before the operation starts.
8c46783 shows two approaches to explaining how the internal methods use the AbortSignal. Let me know which you prefer.
***
[Preview](https://s3.amazonaws.com/pr-preview/jyasskin/webappsec-credential-management/integrate-abort.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/6e831a6...jyasskin:b26c4d1.html)
> Handle the AbortSignal in get() and create() themselves.

- index.src.html
Addresses https://github.com/w3c/webappsec-credential-management/issues/107.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/store-fail.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/6e831a6...761f041.html)
> [[Store]] can fail.

- index.html
- index.src.html
Some credential types wish to be usable in nested contexts. This patch moves the
top-level restriction out of the 'navigator.credentials' API itself, and into the
credential types that wish to have such a restriction.
Note that it also changes the behavior of those restrictions: rather than throwing
a 'NotSupported' error, it instead returns an empty set. That seems both simpler and
less likely to cause developers to be angry at me.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/top-level.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-credential-management/ac0ea41...4bb98cc.html)
> Remove the blanket restriction against nested usage.

- index.src.html
Closes #111 
CC: @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/webappsec-credential-management/pull/119.html" title="Last updated on May 21, 2018, 4:05 AM GMT (1537051)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/119/ad41ec2...saschanaz:1537051.html" title="Last updated on May 21, 2018, 4:05 AM GMT (1537051)">Diff</a>
> Use new mixin IDL syntax

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/webappsec-credential-management/pull/125.html" title="Last updated on Jul 18, 2018, 11:36 PM GMT (d182f77)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/125/e62cb76...marcoscaceres:d182f77.html" title="Last updated on Jul 18, 2018, 11:36 PM GMT (d182f77)">Diff</a>
> fix: getQuerySelector/querySelector in examples

- index.src.html
closes #122
It was defined but never used.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/webappsec-credential-management/pull/123.html" title="Last updated on Jul 18, 2018, 10:16 PM GMT (971f7a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/123/e62cb76...marcoscaceres:971f7a8.html" title="Last updated on Jul 18, 2018, 10:16 PM GMT (971f7a8)">Diff</a>
> Remove typedef CredentialBodyType

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/159.html" title="Last updated on Feb 20, 2021, 5:39 AM UTC (2dd407c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/159/0a402ff...2dd407c.html" title="Last updated on Feb 20, 2021, 5:39 AM UTC (2dd407c)">Diff</a>
> Cite HTML for postMessage(), not WEBMESSAGING fork

- .github/workflows/build-validate-publish.yml
This change adds CI automation to build and validate spec output — both for PRs and pushes to main — and to deploy/publish the spec output to https://w3c.github.io/webappsec-credential-management/ on pushes to main.
https://github.com/w3c/spec-prod is what does the actual work.
> Meta: Build, validate, and publish spec automatically

- .pr-preview.json
We did not update the `.pr-preview.json` config file when we changed the spec source file from `index.src.html` to `index.bs`.
> fix .pr-preview.json to use index.bs, not index.src.html

- .github/workflows/auto-publish.yml
https://github.com/w3c/webappsec-credential-management/runs/4107086975?check_suite_focus=true found a problem with a version of the PR, but then didn't fail the check, so the author didn't see it.
Failing on `link-error` would be fine too, but @nsatragno just made the spec warning-clean, so it'd be good to help keep it that way.
> Fail the CI on bikeshed warnings

- index.bs
Reject aborted operations with the "abort reason" instead of AbortError.
Fixes #175.
***
<a href="https://pr-preview.s3.amazonaws.com/nsatragno/webappsec-credential-management/pull/176.html" title="Last updated on Nov 10, 2021, 3:56 PM UTC (18a0146)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/176/9617033...nsatragno:18a0146.html" title="Last updated on Nov 10, 2021, 3:56 PM UTC (18a0146)">Diff</a>
> Reject aborted operations with the abort reason

- index.bs
If the `CredentialRequestOptions` supplied to the Request a Credential algorithm contains a object named `publicKey` then check that the responsible document is allowed to use the publickey-credentials-get policy-controlled feature.
This PR supersedes PR #138.
Fixes #136 
Improves #135
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/182.html" title="Last updated on Jan 6, 2022, 9:42 PM UTC (e915c78)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/182/b273b4a...e915c78.html" title="Last updated on Jan 6, 2022, 9:42 PM UTC (e915c78)">Diff</a>
> Add permissions-policy check for publicKey credentials

- index.bs
This the core of @jyasskin's answer to [my questions here](https://github.com/w3c/webappsec-credential-management/pull/181#discussion_r781658592) wrt how to re-write the relevant credential interface objects alg to use the new registry.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/webappsec-credential-management/pull/185.html" title="Last updated on Jan 12, 2022, 10:31 PM UTC (da4772a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/185/37a3cb2...jyasskin:da4772a.html" title="Last updated on Jan 12, 2022, 10:31 PM UTC (da4772a)">Diff</a>
> Use the registry to find interface objects for a CredentalOptions.

- index.bs
Please see issue #147 and https://github.com/w3c/webauthn/issues/1004 for full context.
The summary is that this PR introduces a registry mapping credential types to options member identifiers, and updates the magical [relevant credential interface objects](https://w3c.github.io/webappsec-credential-management/#credentialrequestoptions-relevant-credential-interface-objects) algorithm to use the latter registry.
This is the "...define a mapping from dictionary member names to `[[type]]` values or vice versa." solution identified by @bzbarsky in https://github.com/w3c/webauthn/issues/1004#issuecomment-410010806.  @jyasskin had also [independently suggested using a registry for this mapping](https://www.w3.org/TR/credential-management-1/#issue-962f77e2).
Additionally, this PR contains some …
> Map options member identifiers and credential types: public-key vs publicKey

- index.bs
This is a very quickly done separation of section [6. Security and Privacy Considerations](https://w3c.github.io/webappsec-credential-management/#security-and-privacy) into two separate "security cons" and "privacy cons" sections in order to get our editors' draft to be published.
upon a quick scan it seemed the last two subsections were the only privacy-oriented ones, so I carved them into the new "privacy cons" section.
This will need review and polishing no doubt, but hopefully will re-instate editors' draft auto-updating. 
fixes #186
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/187.html" title="Last updated on Jan 19, 2022, 8:56 PM UTC (c04caaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/1 …
> create separate security and privacy considerations sections

- index.bs
As a follow up to https://github.com/w3c/webauthn/pull/1706#discussion_r828811241, this PR aims to address the necessary changes on the Credential Management side to throw exceptions in all of the Credential internal methods: [`[[CollectFromCredentialStore]]`](https://w3c.github.io/webappsec-credential-management/#algorithm-collect-creds), [`[[DiscoverFromExternalSource]]`](https://w3c.github.io/webappsec-credential-management/#algorithm-discover-creds), [`[[Create]]`](https://w3c.github.io/webappsec-credential-management/#algorithm-create-cred), and [`[[Store]]`](https://w3c.github.io/webappsec-credential-management/#algorithm-store-cred). 
All of the credential types have also been updated in the places:
- Web Authentication: https://github.com/w3c/webauthn/pull/1706
- WebOTP: …
> Throw exceptions instead of returning them

- index.bs
@npm1 FYI
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/webappsec-credential-management/pull/203.html" title="Last updated on Jul 8, 2022, 12:26 PM UTC (3d06fd7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/203/878530d...johannhof:3d06fd7.html" title="Last updated on Jul 8, 2022, 12:26 PM UTC (3d06fd7)">Diff</a>
> Correctly indent "Terminate these substeps" (fixes #202)

- index.bs
Companion change to https://github.com/fedidcg/FedCM/pull/236
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/webappsec-credential-management/pull/204.html" title="Last updated on Aug 29, 2022, 10:05 PM UTC (e77001f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/204/8350696...johannhof:e77001f.html" title="Last updated on Aug 29, 2022, 10:05 PM UTC (e77001f)">Diff</a>
> Add permissions policy check for FedCM

- index.bs
These are no longer necessary, see https://github.com/w3c/webappsec-credential-management/pull/204#discussion_r961758297
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/webappsec-credential-management/pull/208.html" title="Last updated on Sep 7, 2022, 1:01 PM UTC (ce85c6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/208/05f4402...johannhof:ce85c6a.html" title="Last updated on Sep 7, 2022, 1:01 PM UTC (ce85c6a)">Diff</a>
> Remove custom anchors for FedCM

- index.bs
Fixes https://github.com/w3c/webappsec-credential-management/issues/206
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/webappsec-credential-management/pull/207.html" title="Last updated on Sep 16, 2022, 4:56 PM UTC (75a6b6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/207/8350696...npm1:75a6b6a.html" title="Last updated on Sep 16, 2022, 4:56 PM UTC (75a6b6a)">Diff</a>
> Disallow multiple in-progress credential requests

- index.bs
This PR adds support for `publickey-credentials-create` permission policy,
to support https://github.com/w3c/webauthn/pull/1801
See also https://github.com/w3c/webauthn/issues/1656
***
<a href="https://pr-preview.s3.amazonaws.com/stephenmcgruer/webappsec-credential-management/pull/209.html" title="Last updated on Feb 27, 2023, 3:51 PM UTC (305097c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/209/976f91b...stephenmcgruer:305097c.html" title="Last updated on Feb 27, 2023, 3:51 PM UTC (305097c)">Diff</a>
> Add support for publickey-credentials-create permission policy

- index.bs
Fixes #214 #98
***
<a href="https://pr-preview.s3.amazonaws.com/lukewarlow/webappsec-credential-management/pull/215.html" title="Last updated on Jul 5, 2023, 12:38 AM UTC (95b7e79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/215/5dee10a...lukewarlow:95b7e79.html" title="Last updated on Jul 5, 2023, 12:38 AM UTC (95b7e79)">Diff</a>
> Fix return type of CredentialsContainer.store

- index.bs
Throw a NotSupportedError by default for store rather than return undefined.
***
<a href="https://pr-preview.s3.amazonaws.com/lukewarlow/webappsec-credential-management/pull/219.html" title="Last updated on Jul 5, 2023, 5:54 PM UTC (38e5755)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/219/c009d69...lukewarlow:38e5755.html" title="Last updated on Jul 5, 2023, 5:54 PM UTC (38e5755)">Diff</a>
> Change default store algorithm to throw (#218)

- index.bs
Fixes https://github.com/w3c/webappsec-credential-management/issues/213
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/223.html" title="Last updated on Jul 12, 2023, 5:06 AM UTC (b0cb461)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/223/c009d69...b0cb461.html" title="Last updated on Jul 12, 2023, 5:06 AM UTC (b0cb461)">Diff</a>
> Use “navigable”+“parent”, not “parent browsing context”; fix fetch() refs

- index.bs
Closes #166
cc @fred-wang
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/234.html" title="Last updated on May 22, 2024, 1:18 AM UTC (47b4cf7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/234/123c9ea...47b4cf7.html" title="Last updated on May 22, 2024, 1:18 AM UTC (47b4cf7)">Diff</a>
> Editorial: Replace "a priori authenticated URL" with "potentially trustworthy URL

- index.bs
The "prevent silent access" didn't link properly. Sorry about that.
Bikeshed doesn't seem to support backticks in the linking shorthands.
These are better also, as it scopes the concept properly to origin.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/235.html" title="Last updated on May 22, 2024, 1:31 AM UTC (54a5791)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/235/671ba03...54a5791.html" title="Last updated on May 22, 2024, 1:31 AM UTC (54a5791)">Diff</a>
> Editorial: fixup prevent silent access xrefs

- index.bs
closes #227 
Adds fully active checks for `CredentialsContainer`:
- .get()
- .store()
- .create()
- .preventSilentAccess()
> Add fully active checks

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/236.html" title="Last updated on May 23, 2024, 1:26 AM UTC (736fcda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/236/674c63c...736fcda.html" title="Last updated on May 23, 2024, 1:26 AM UTC (736fcda)">Diff</a>
> Full active check should happen before AbortSignal check

- index.bs
This fixes 
Most of the heavy lifting of conditional in create is handled in WebAuthn.
Fixes #225
See also:
https://github.com/w3c/webauthn/pull/1951/files
https://github.com/w3c/webauthn/wiki/Explainer:-Conditional-Registration-Extension
***
<a href="https://pr-preview.s3.amazonaws.com/pascoej/webappsec-credential-management/pull/224.html" title="Last updated on May 30, 2024, 5:14 PM UTC (ffa7bbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/224/a70bc66...pascoej:ffa7bbc.html" title="Last updated on May 30, 2024, 5:14 PM UTC (ffa7bbc)">Diff</a>
> Add mediation to credential creation options

- index.bs
Need this for Digital Credential spec, so we can say that DigitalCredential is origin-bound.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/240.html" title="Last updated on Jun 7, 2024, 7:08 AM UTC (7d95c24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/240/4fa577c...7d95c24.html" title="Last updated on Jun 7, 2024, 7:08 AM UTC (7d95c24)">Diff</a>
> Chore: export "origin-bound" definition

- index.bs
Now allows registration of Permission Policy, and added Digital Credentials. 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/242.html" title="Last updated on Jul 22, 2024, 3:27 AM UTC (a4d1981)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/242/75bcf50...a4d1981.html" title="Last updated on Jul 22, 2024, 3:27 AM UTC (a4d1981)">Diff</a>
> Use credential type registry for permissions + digital credentials

- index.bs
In order to make errors more distinguishable, it would be good if we could use "InvalidStateError" instead for fully active checks.  
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/245.html" title="Last updated on Jul 26, 2024, 7:22 AM UTC (26de7f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/245/7fb261a...26de7f1.html" title="Last updated on Jul 26, 2024, 7:22 AM UTC (26de7f1)">Diff</a>
> Use 'InvalidStateError' for fully active check

- index.bs
Closes #249 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/250.html" title="Last updated on Jul 29, 2024, 2:54 AM UTC (d51a89f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/250/991c1ec...d51a89f.html" title="Last updated on Jul 29, 2024, 2:54 AM UTC (d51a89f)">Diff</a>
> Disallow empty credential selection

- index.bs
Small cleanup... the "immediately [=resolves=]" was unnecessary, as "[=a promise resolved with=]" handles that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/252.html" title="Last updated on Jul 29, 2024, 10:37 AM UTC (3b1b179)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/252/7432408...3b1b179.html" title="Last updated on Jul 29, 2024, 10:37 AM UTC (3b1b179)">Diff</a>
> Editorial: clean up some promise jargon
